from __future__ import annotations as _annotations

from ._version import __version__
from .registry import CommandSpec, get_schema, registry, search, search_names
from .schemas import (
    CatCommand,
    CdCommand,
    ChmodCommand,
    CopyCommand,
    DuCommand,
    EchoCommand,
    FindCommand,
    GrepCommand,
    HeadCommand,
    LnCommand,
    LsCommand,
    MkdirCommand,
    MoveCommand,
    NlCommand,
    PwdCommand,
    RemoveCommand,
    RgCommand,
    SedCommand,
    SortCommand,
    StatCommand,
    StructuredCommand,
    TailCommand,
    TouchCommand,
    WcCommand,
)

__all__ = (
    "__version__",
    "CatCommand",
    "CdCommand",
    "ChmodCommand",
    "CommandSpec",
    "CopyCommand",
    "DuCommand",
    "EchoCommand",
    "FindCommand",
    "GrepCommand",
    "HeadCommand",
    "LnCommand",
    "LsCommand",
    "MkdirCommand",
    "MoveCommand",
    "NlCommand",
    "PwdCommand",
    "RemoveCommand",
    "RgCommand",
    "SedCommand",
    "SortCommand",
    "StatCommand",
    "StructuredCommand",
    "TailCommand",
    "TouchCommand",
    "WcCommand",
    "get_schema",
    "registry",
    "search",
    "search_names",
)
