"""Typed surface of the PyO3-backed VSH native module."""

from __future__ import annotations

import builtins
from collections.abc import Mapping
from enum import Enum
from os import PathLike
from typing import overload

__version__: str

class VshRuntimeError(RuntimeError):
    """Base exception for typed native VSH failures."""

class VshExecutionError(VshRuntimeError):
    """Monty compilation, execution, or hard-budget failure."""

class VshBashError(VshExecutionError):
    diagnostics: BashDiagnostics

class Language(Enum):
    MONTY: Language
    BASH: Language

class BashLimits:
    def __init__(
        self,
        *,
        max_work_units: int = ...,
        max_aggregate_input_bytes: int = ...,
        max_live_intermediate_bytes: int = ...,
        max_commands: int = ...,
        max_loop_iterations: int = ...,
        max_total_loop_iterations: int = ...,
        max_parser_operations: int = ...,
    ) -> None: ...
    @property
    def max_work_units(self) -> int: ...
    @property
    def max_aggregate_input_bytes(self) -> int: ...
    @property
    def max_live_intermediate_bytes(self) -> int: ...
    @property
    def max_commands(self) -> int: ...
    @property
    def max_loop_iterations(self) -> int: ...
    @property
    def max_total_loop_iterations(self) -> int: ...
    @property
    def max_parser_operations(self) -> int: ...

class BashConfig:
    def __init__(
        self,
        *,
        worker_path: str | PathLike[str] | None = ...,
        limits: BashLimits | None = ...,
        wall_timeout_ms: int | None = ...,
        max_active_workers: int = ...,
        max_idle_workers: int = ...,
    ) -> None: ...
    @property
    def worker_path(self) -> PathLike[str] | None: ...
    @property
    def limits(self) -> BashLimits: ...
    @property
    def wall_timeout_ms(self) -> int | None: ...
    @property
    def max_active_workers(self) -> int: ...
    @property
    def max_idle_workers(self) -> int: ...

class BashResult:
    @property
    def profile(self) -> str: ...
    @property
    def exit_code(self) -> int: ...
    @property
    def stdout(self) -> bytes: ...
    @property
    def stderr(self) -> bytes: ...

class BashDiagnostics:
    @property
    def kind(self) -> str: ...
    @property
    def exit_code(self) -> int | None: ...
    @property
    def stdout(self) -> bytes: ...
    @property
    def stderr(self) -> bytes: ...
    @property
    def changes(self) -> list[CanonicalChange]: ...
    @property
    def changes_complete(self) -> bool: ...
    @property
    def denied_accesses(self) -> int: ...

class ExecutionContext:
    @property
    def language(self) -> Language: ...
    @property
    def profile(self) -> str | None: ...
    @property
    def exit_code(self) -> int | None: ...
    @property
    def complete(self) -> bool: ...
    @property
    def evidence(self) -> str | None: ...
    @property
    def stdout_bytes(self) -> int: ...
    @property
    def stderr_bytes(self) -> int: ...

class _Cancellation:
    def __init__(self) -> None: ...
    def cancel(self) -> bool: ...
    @property
    def commit_entered(self) -> bool: ...

class VshStateError(VshRuntimeError):
    """Transaction lifecycle, approval, reservation, or replay failure."""

class VshStaleError(VshRuntimeError):
    """Host dependencies changed after virtual execution."""

class VshRecoveryError(VshRuntimeError):
    """Durable recovery is required or could not prove ownership."""

class VshInternalError(VshRuntimeError):
    """A contained internal panic or invariant failure."""

class RunMode(Enum):
    PREVIEW: RunMode
    AUTO: RunMode

class HookScope(Enum):
    REVIEW_REQUIRED: HookScope
    ALL_REQUESTS: HookScope

class ReceiptDetail(Enum):
    COMPACT: ReceiptDetail
    FULL: ReceiptDetail

class ExecutionBudget:
    def __init__(
        self,
        *,
        max_program_bytes: int | None = ...,
        max_duration_ms: int | None = ...,
        max_recursion_depth: int | None = ...,
        max_memory_bytes: int | None = ...,
        max_os_calls: int | None = ...,
        max_read_bytes: int | None = ...,
        max_write_bytes: int | None = ...,
        max_io_call_bytes: int | None = ...,
        max_path_bytes: int | None = ...,
        max_directory_entries: int | None = ...,
        max_evidence_records: int | None = ...,
        max_evidence_bytes: int | None = ...,
        max_output_bytes: int | None = ...,
        max_result_bytes: int | None = ...,
        max_exception_bytes: int | None = ...,
    ) -> None: ...
    @property
    def max_program_bytes(self) -> int: ...
    @property
    def max_duration_ms(self) -> int: ...
    @property
    def max_recursion_depth(self) -> int: ...
    @property
    def max_memory_bytes(self) -> int: ...
    @property
    def max_os_calls(self) -> int: ...
    @property
    def max_read_bytes(self) -> int: ...
    @property
    def max_write_bytes(self) -> int: ...
    @property
    def max_io_call_bytes(self) -> int: ...
    @property
    def max_path_bytes(self) -> int: ...
    @property
    def max_directory_entries(self) -> int: ...
    @property
    def max_evidence_records(self) -> int: ...
    @property
    def max_evidence_bytes(self) -> int: ...
    @property
    def max_output_bytes(self) -> int: ...
    @property
    def max_result_bytes(self) -> int: ...
    @property
    def max_exception_bytes(self) -> int: ...

class RunRequest:
    def __init__(
        self,
        code: str,
        *,
        language: Language | None = ...,
        intent: str | None = ...,
        mode: RunMode | None = ...,
        detail: ReceiptDetail | None = ...,
        budget: ExecutionBudget | None = ...,
    ) -> None: ...
    @property
    def code(self) -> str: ...
    @property
    def language(self) -> Language: ...
    @property
    def intent(self) -> str | None: ...
    @property
    def mode(self) -> RunMode: ...
    @property
    def detail(self) -> ReceiptDetail: ...
    @property
    def budget(self) -> ExecutionBudget: ...

class NodeSummary:
    @property
    def kind(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def mode(self) -> int: ...
    @property
    def content(self) -> str | None: ...

class CanonicalChange:
    @property
    def path(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def before(self) -> NodeSummary | None: ...
    @property
    def after(self) -> NodeSummary | None: ...

class EffectSummary:
    @property
    def sequence(self) -> int: ...
    @property
    def origin(self) -> str: ...
    @property
    def operation(self) -> str: ...
    @property
    def paths(self) -> list[str]: ...
    @property
    def before(self) -> NodeSummary | None: ...
    @property
    def after(self) -> NodeSummary | None: ...
    @property
    def observed_content(self) -> str | None: ...

class ReviewContent:
    @property
    def path(self) -> str: ...
    @property
    def blob(self) -> str: ...
    @property
    def bytes(self) -> builtins.bytes: ...

class RequestEvent:
    @property
    def execution_context(self) -> ExecutionContext: ...
    @property
    def contents(self) -> list[ReviewContent]: ...
    @property
    def content_complete(self) -> bool: ...
    @property
    def schema_version(self) -> int: ...
    @property
    def event_id(self) -> str: ...
    @property
    def hook_id(self) -> str: ...
    @property
    def transaction(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def baseline(self) -> str: ...
    @property
    def base_snapshot(self) -> str: ...
    @property
    def diff(self) -> str: ...
    @property
    def read_set(self) -> str: ...
    @property
    def write_set(self) -> str: ...
    @property
    def program(self) -> str: ...
    @property
    def policy(self) -> str: ...
    @property
    def runtime_config(self) -> str: ...
    @property
    def intent_digest(self) -> str | None: ...
    @property
    def intent(self) -> str | None: ...
    @property
    def policy_profile(self) -> str: ...
    @property
    def policy_thresholds(self) -> dict[str, int]: ...
    @property
    def risk_flags(self) -> list[str]: ...
    @property
    def touched_paths(self) -> int: ...
    @property
    def created_paths(self) -> int: ...
    @property
    def modified_paths(self) -> int: ...
    @property
    def deleted_paths(self) -> int: ...
    @property
    def renamed_paths(self) -> int: ...
    @property
    def changed_bytes(self) -> int: ...
    @property
    def delete_ratio_bps(self) -> int: ...
    @property
    def executable_changes(self) -> int: ...
    @property
    def symlink_changes(self) -> int: ...
    @property
    def canonical_diff(self) -> list[CanonicalChange]: ...
    @property
    def effects(self) -> list[EffectSummary]: ...
    @property
    def os_calls(self) -> int: ...
    @property
    def read_bytes(self) -> int: ...
    @property
    def write_bytes(self) -> int: ...
    @property
    def directory_entries(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def denied_accesses(self) -> int: ...
    @property
    def result_bytes(self) -> int: ...
    @property
    def evidence_complete(self) -> bool: ...
    @property
    def evidence_truncated(self) -> bool: ...

class CommitPreparation:
    @property
    def transaction(self) -> str: ...
    @property
    def event(self) -> RequestEvent | None: ...

class HookDecision:
    @property
    def verdict(self) -> str: ...
    @property
    def reason(self) -> str: ...
    @staticmethod
    def follow_policy() -> HookDecision: ...
    @staticmethod
    def approve(reason: str) -> HookDecision: ...
    @staticmethod
    def review(feedback: str) -> HookDecision: ...
    @staticmethod
    def reject(reason: str) -> HookDecision: ...

class HookDecisionRecord:
    @property
    def event_id(self) -> str: ...
    @property
    def hook_id(self) -> str: ...
    @property
    def verdict(self) -> str: ...
    @property
    def reason(self) -> str: ...
    @property
    def principal(self) -> str | None: ...

class Receipt:
    @property
    def language(self) -> Language: ...
    @property
    def stderr(self) -> str: ...
    @property
    def stdout_bytes(self) -> bytes: ...
    @property
    def stderr_bytes(self) -> bytes: ...
    @property
    def transaction(self) -> str: ...
    @property
    def base_snapshot(self) -> str: ...
    @property
    def state(self) -> str: ...
    @property
    def decision(self) -> str: ...
    @property
    def diff(self) -> str: ...
    @property
    def changed_paths(self) -> int: ...
    @property
    def changes(self) -> list[tuple[str, str]]: ...
    @property
    def result(self) -> object: ...
    @property
    def result_repr(self) -> str: ...
    @property
    def stdout(self) -> str: ...
    @property
    def risk_flags(self) -> list[str]: ...
    @property
    def deny_reason(self) -> str | None: ...
    @property
    def os_calls(self) -> int: ...
    @property
    def read_bytes(self) -> int: ...
    @property
    def write_bytes(self) -> int: ...
    @property
    def directory_entries(self) -> int: ...
    @property
    def output_bytes(self) -> int: ...
    @property
    def denied_accesses(self) -> int: ...
    @property
    def result_bytes(self) -> int: ...
    @property
    def committed(self) -> bool: ...
    @property
    def commit_operations(self) -> int | None: ...
    @property
    def verified_paths(self) -> int | None: ...
    @property
    def cleanup_pending(self) -> bool: ...
    def timings_ns(self) -> Mapping[str, int]: ...

class RecoveryReport:
    @property
    def finalized_commits(self) -> int: ...
    @property
    def rolled_back(self) -> int: ...
    @property
    def cleaned(self) -> int: ...
    @property
    def orphaned(self) -> int: ...
    @property
    def conflicts(self) -> list[tuple[str, str | None, str]]: ...

class CommitResolution:
    @property
    def receipt(self) -> Receipt: ...
    @property
    def hook(self) -> HookDecisionRecord | None: ...

class Runtime:
    @staticmethod
    def open(
        workspace: str | PathLike[str],
        *,
        data_directory: str | PathLike[str] | None = ...,
        policy: str = ...,
        worker_path: str | PathLike[str] | None = ...,
        bash: BashConfig | None = ...,
        hook_id: str | None = ...,
        hook_scope: HookScope | None = ...,
        review_content_bytes: int = ...,
    ) -> Runtime: ...
    def run(self, request: RunRequest) -> Receipt: ...
    def _run(self, request: RunRequest, cancellation: _Cancellation) -> Receipt: ...
    def _preview(
        self,
        request: RunRequest | str,
        cancellation: _Cancellation,
        *,
        language: Language | None = ...,
        intent: str | None = ...,
        detail: ReceiptDetail | None = ...,
        budget: ExecutionBudget | None = ...,
    ) -> Receipt: ...
    def _commit(
        self, transaction: str, now_unix_ms: int, cancellation: _Cancellation
    ) -> Receipt: ...
    def _resolve_commit(
        self,
        preparation: CommitPreparation,
        decision: HookDecision,
        now_unix_ms: int,
        cancellation: _Cancellation,
    ) -> CommitResolution: ...
    @overload
    def preview(self, request: RunRequest) -> Receipt: ...
    @overload
    def preview(
        self,
        request: str,
        *,
        language: Language | None = ...,
        intent: str | None = ...,
        detail: ReceiptDetail | None = ...,
        budget: ExecutionBudget | None = ...,
    ) -> Receipt: ...
    def discard_preview(self, transaction: str) -> bool: ...
    def _cancel_receipt(self, transaction: str) -> None: ...
    def approve(
        self,
        transaction: str,
        principal: str,
        issued_at_unix_ms: int,
        expires_at_unix_ms: int,
    ) -> str: ...
    def commit(self, transaction: str, now_unix_ms: int) -> Receipt: ...
    def prepare_commit(self, transaction: str) -> CommitPreparation: ...
    def resolve_commit(
        self,
        preparation: CommitPreparation,
        decision: HookDecision,
        now_unix_ms: int,
    ) -> CommitResolution: ...
    def fail_hook(self, preparation: CommitPreparation) -> None: ...
    def transaction_state(self, transaction: str) -> str: ...
    def recover(self) -> RecoveryReport: ...

def version() -> str:
    """Return the native VSH semantic version."""

def engine_kind() -> str:
    """Return the native engine identity."""

def normalize_path(path: str) -> str:
    """Normalize a workspace-relative virtual path."""
