[package]
name = "vsh-vfs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Immutable snapshot and copy-on-write virtual filesystem for VSH"
publish = ["crates-io"]

[dependencies]
vsh-store.workspace = true
vsh-types.workspace = true

[lints]
workspace = true
