[package]
name = "vsh-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Transaction state storage contracts for VSH"
publish = ["crates-io"]

[dependencies]
blake3.workspace = true
cap-std.workspace = true
vsh-types.workspace = true

[target.'cfg(windows)'.dependencies]
cap-fs-ext.workspace = true

[lints]
workspace = true
